const fs=require('fs'),vm=require('vm'),assert=require('assert/strict'),path=require('path');
const canvas=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/@napi-rs/canvas');
const html=fs.readFileSync(path.join(__dirname,'../../index.html'),'utf8');
const line=name=>html.split('\n').find(l=>l.startsWith(name));
const fn=name=>{const start=html.search(new RegExp('^(?:async )?function '+name+'\\(','m'));assert(start>=0,name);const first=html.indexOf('\n',start);return html.slice(start,html.slice(start,first).endsWith('}')?first:html.indexOf('\n}',start)+2)};
const nodes=new Map();function node(id){if(!nodes.has(id))nodes.set(id,{id,value:'',textContent:'',innerHTML:'',disabled:false,classList:{add(){},remove(){},toggle(){}},showModal(){this.open=true},close(){this.open=false},click(){}});return nodes.get(id)}
const document={getElementById:node,createElement(type){return type==='canvas'?canvas.createCanvas(1,1):{...node('element'),style:{},dispatchEvent(){}}},createEvent(){return{initMouseEvent(){}}}};
const original={charge:{id:'test-charge',client_id:'client',vehicle_id:'vehicle',service_id:'service',status:'pending',frequency:'biweekly',visits_per_month:2,gross_monthly_amount:420,amount:390,credit_applied:0,due_date:'2026-10-05'},client:{name:'Cliente Demonstração'},vehicle:{brand:'Toyota',model:'Corolla Cross',plate:'TESTE00'},service:{name:'Pacote Premium'},bank:{pix_key:'exemplo@teste.invalid',bank_name:'Banco de demonstração',branch:'0000',account_number:'00000-0',account_holder:'Vaporeasy — demonstração'}};
let data=structuredClone(original),writes=[],files=[],downloads=[];
class TestImage extends canvas.Image{decode(){return this.complete?Promise.resolve():new Promise((resolve,reject)=>{this.onload=resolve;this.onerror=reject})}}
const sandbox={document,Image:TestImage,console,Blob,File,URL,Intl,Map,Date,Number,String,Math,Promise,Error,setTimeout:(fn)=>fn(),requestAnimationFrame:fn=>fn(),atob,btoa,navigator:{userAgent:'node',canShare:()=>true,share:async({files:attached})=>{assert(attached?.length);files.push(...attached)}},structuredClone};
sandbox.window=sandbox;sandbox.self=sandbox;sandbox.globalThis=sandbox;
const nativeCreate=document.createElement;document.createElement=t=>{const n=nativeCreate(t);if(t==='canvas')n.toBlob=cb=>cb(new Blob([n.toBuffer('image/png')],{type:'image/png'}));if(t==='a')n.click=()=>downloads.push(n.download);return n};
const context=vm.createContext(sandbox);
vm.runInContext(fs.readFileSync(process.argv[2]||'/workspace/scratch/c344b93cb9ab/jspdf.js','utf8'),context);
const names=['show','financePackageDate','packageFrequencyMeta','packageChargeCommercialDiscount','getPackageChargeShareData','packageDocumentModel','packageChargeHtml','packageChargeCanvas','sharePackageCharge','renderPackageReceipt','shareReceiptCanvasFile','sharePackageReceiptFile','cleanFileName','canvasRoundRect','canvasText','canvasBlob','settleCanvas','shareReceiptVisual','generateReceiptPdf','paymentDiscountCalc','savePayment'];
sandbox.sb={from(table){return{select(){return this},eq(){return this},async single(){return{data:structuredClone(({package_charges:data.charge,clients:data.client,vehicles:data.vehicle,services:data.service,business_payment_settings:data.bank})[table])}}}},async rpc(name,args){writes.push({name,args});assert.equal(name,'confirm_package_charge');Object.assign(data.charge,{status:'paid',payment_method:args.p_payment_method,paid_at:'2026-10-05T17:30:00Z'});return{data:[data.charge]}}};
vm.runInContext([line('const BRAND_LOGO='),line('const esc='),line('const money='),'const $=id=>document.getElementById(id),fail=e=>e.message,financeAllowed=()=>currentRole==="owner";let currentRole="owner",currentReceipt=null,currentReceiptGroup=null,currentPackageReceipt=null,currentPaymentQuote=null,currentPaymentMode="package_receive",currentPaymentGroupIds=[];const agendaMonthCache=new Map(),loadApps=async()=>{},loadFinance=async()=>{};',...names.map(fn)].join('\n'),context);
const run=src=>vm.runInContext(src,context),results=[];const check=(v,label)=>{assert(v,label);results.push(label)};
(async()=>{
await run('sharePackageCharge("test-charge")');check(node('rd').open&&node('rcontent').innerHTML.includes('DADOS PARA PAGAMENTO'),'Abre modal pendente');check(files.length===0,'Abrir não compartilha automaticamente');
await run('shareReceiptVisual()');if(!files[0])throw Error(node('rgroupmsg').textContent);check(files[0].type==='image/png'&&files[0].size>10000,'PNG gerado e anexado');
await run('generateReceiptPdf()');check(files[1].type==='application/pdf'&&(await files[1].text()).startsWith('%PDF'),'PDF gerado e anexado');check(writes.length===0,'Exportação não altera financeiro');
node('payid').value='test-charge';node('paymethod').value='Pix';node('paynotes').value='';node('paydiscounttype').value='none';run('currentPaymentQuote={gross:390}');sandbox.event={preventDefault(){},submitter:node('paysubmit')};await run('savePayment(event)');check(writes.length===1&&writes[0].name==='confirm_package_charge','Usa somente confirmação existente');check(node('rcontent').innerHTML.includes('PAGAMENTO RECEBIDO')&&data.charge.id==='test-charge'&&data.charge.amount===390,'Mesma mensalidade torna-se recibo');
await run('shareReceiptVisual()');await run('generateReceiptPdf()');check(files[2].name.startsWith('recibo-plano')&&files[3].name.endsWith('.pdf'),'Recibo PNG e PDF');
data=structuredClone(original);await run('sharePackageCharge("test-charge")');Object.assign(data.charge,{status:'paid',payment_method:'Pix'});await run('shareReceiptVisual()');check(files[4].name.startsWith('recibo-plano'),'Relê pagamento antes de exportar');
sandbox.navigator.canShare=()=>false;await run('shareReceiptVisual()');check(downloads.length===1&&downloads[0].endsWith('.png'),'Sem suporte a compartilhamento baixa arquivo, nunca texto');
node('rd').close();data.charge.status='cancelled';await run('sharePackageCharge("test-charge")');check(!node('rd').open,'Cancelada bloqueada');run('currentRole="collaborator"');data.charge.status='pending';await run('sharePackageCharge("test-charge")');check(!node('rd').open,'Colaborador bloqueado');run('currentRole="owner"');
sandbox.long=structuredClone(original);sandbox.long.client.name='Nome longo '.repeat(12);sandbox.long.bank.pix_key='a'.repeat(150);sandbox.long.charge.frequency='weekly';sandbox.long.charge.visits_per_month=4;sandbox.long.charge.credit_applied=100;sandbox.long.charge.amount=290;const cv=await run('packageChargeCanvas(long)');check(cv.height>1000,'Canvas dinâmico com campos longos');
const out=path.join(__dirname,'evidence');fs.mkdirSync(out,{recursive:true});for(const f of files.slice(0,4))fs.writeFileSync(path.join(out,f.name),Buffer.from(await f.arrayBuffer()));fs.writeFileSync(path.join(out,'long.png'),cv.toBuffer('image/png'));fs.writeFileSync(path.join(out,'results.json'),JSON.stringify({scope:'Componente real com DOM/API simulados; canvas e PDF reais; não E2E autenticado',passed:results},null,2));console.log(JSON.stringify(results,null,2));
})().catch(e=>{console.error(e);process.exit(1)});
