const fs=require('fs'),assert=require('assert/strict');
const {chromium}=require(process.env.CODEX_PRIMARY_RUNTIME_NODE_MODULES+'/playwright');
(async()=>{
 const html=fs.readFileSync('index.html','utf8'),browser=await chromium.launch({headless:true}),page=await browser.newPage({viewport:{width:393,height:852}});
 await page.setContent(html.replace(/<script\b[^>]*>[\s\S]*?<\/script>/g,''));
 const functions=html.slice(html.indexOf('function adminScheduleOverrideAllowed()'),html.indexOf('async function fillVehicles(cid)'));
 const save=html.slice(html.indexOf('async function saveAppt(e)'),html.indexOf('function realizedVehicleIds()'));
 await page.evaluate(({functions,save})=>{
  window.$=id=>document.getElementById(id); window.currentRole='owner';window.services=[{id:'service',category:'Estética',duration_minutes:90,price:150}];window.slotRequestSeq=0;
  window.selectedAssignment=()=>({team_id:'team',collaborator_id:null});window.selectedBatchVehicleIds=()=>['vehicle'];window.selectedBatchRecurrences=()=>[{vehicle_id:'vehicle',frequency:'once'}];
  window.serviceIsPackage=s=>String(s?.category||'').startsWith('Pacote');window.serviceUsesVehicleSizePricing=()=>false;window.appointmentSubmitLabel=()=> 'Agendar';window.esc=String;window.fail=e=>e.message;window.today=()=> '2026-10-08';window.financeAllowed=()=>false;window.agendaMonthCache=new Map();window.tab=()=>{};window.messages=[];window.show=(id,text)=>window.messages.push(text);
  window.calls=[];window.sb={rpc:async(name,args)=>{calls.push({name,args});return {data:name.includes('slots')?[]:{count:1,appointment_ids:['test'],package_billing:[]}}}};
  window.__appointmentIdempotencyKey='test-key';window.__appointmentSaveInFlight=false;
  $('as').innerHTML='<option value="service">Estética</option>';$('ac').innerHTML='<option value="client">Client</option>';$('adt').value='2026-10-09';$('aid').value='';
  window.eval(functions+'\n'+save);
  window.syncAdminScheduleOverride=syncAdminScheduleOverride;window.loadAvailableSlots=loadAvailableSlots;window.saveAppt=saveAppt;
 },{functions,save});
 await page.evaluate(()=>loadAvailableSlots());
 assert.equal(await page.locator('#apsave').isDisabled(),true);
 await page.locator('#apoverride').check({force:true});
 await page.waitForFunction(()=>document.getElementById('apsave').disabled===false);
 assert.equal(await page.locator('#apoverridetime').getAttribute('type'),'time');
 assert.equal(await page.locator('#atm').evaluate(e=>e.required),false);
 await page.evaluate(()=>{$('apoverridetime').value='10:10';$('apoverridereason').value='Equipe confirmou capacidade extra.';window.confirm=()=>true;});
 await page.evaluate(()=>saveAppt({preventDefault(){}}));
 const saved=await page.evaluate(()=>calls.find(x=>x.name==='create_admin_schedule_override'));
 assert.equal(saved.args.p_local_time,'10:10');assert.equal(saved.args.p_reason,'Equipe confirmou capacidade extra.');assert.equal('p_recurrences' in saved.args,false);
 await page.evaluate(()=>{calls.length=0;window.confirm=()=>false;window.__appointmentIdempotencyKey='test-2';});
 await page.evaluate(()=>saveAppt({preventDefault(){}}));assert.equal(await page.evaluate(()=>calls.length),0);
 await page.evaluate(()=>{window.confirm=()=>true;window.selectedBatchRecurrences=()=>[{vehicle_id:'vehicle',frequency:'weekly'}];});
 await page.evaluate(()=>saveAppt({preventDefault(){}}));assert.equal(await page.evaluate(()=>calls.length),0);
 await page.evaluate(()=>{currentRole='operator';syncAdminScheduleOverride();});
 assert.equal(await page.locator('#apoverridewrap').evaluate(e=>e.classList.contains('hidden')),true);
 assert.equal(await page.locator('#apoverride').isChecked(),false);
 await page.evaluate(()=>{currentRole='owner';services[0].category='Pacote Premium';syncAdminScheduleOverride();});
 assert.equal(await page.locator('#apoverridewrap').evaluate(e=>e.classList.contains('hidden')),true);
 await page.evaluate(()=>{services[0].category='Estética';$('aid').value='existing';syncAdminScheduleOverride();});
 assert.equal(await page.locator('#apoverridewrap').evaluate(e=>e.classList.contains('hidden')),true);
 console.log('PASS: browser DOM — full day unlock, manual time, RPC payload, confirmation cancellation, recurrence guard, operator/plan/edit hidden.');
 await browser.close();
})().catch(e=>{console.error(e);process.exit(1)});
