begin;
create temporary table plan_test_results(test text,result text);
do $test$
declare c uuid; v uuid; v2 uuid; svc uuid; rp uuid; rp2 uuid; sub uuid; sub2 uuid; ap uuid; e uuid; e2 uuid;
 owner_id uuid:='11111111-1111-4111-8111-111111111111'; operator_id uuid:='33333333-3333-4333-8333-333333333333';
 m date:=date_trunc('month',(now() at time zone 'America/Sao_Paulo'))::date; d date; r jsonb; s jsonb; blocked boolean; key uuid:=gen_random_uuid(); before_charges bigint; before_appointments bigint; fixture record;
begin
 d:=m-interval '1 month';
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 insert into public.clients(name) values('TEST PLAN CONTROL') returning id into c;
 insert into public.vehicles(client_id,brand,model) values(c,'TEST','ONE') returning id into v;
 insert into public.vehicles(client_id,brand,model) values(c,'TEST','TWO') returning id into v2;
 insert into public.services(name,category,price,duration_minutes) values('TEST PLAN','Estética',150,60) returning id into svc;
 insert into public.recurring_plans(client_id,vehicle_id,service_id,frequency,weekday,local_time,start_date,active) values(c,v,svc,'weekly',1,'08:00',d,false) returning id into rp;
 insert into public.recurring_plans(client_id,vehicle_id,service_id,frequency,weekday,local_time,start_date,active) values(c,v2,svc,'weekly',1,'08:00',d,false) returning id into rp2;
 insert into public.package_subscriptions(client_id,vehicle_id,service_id,recurring_plan_id,frequency,visits_per_month,package_units,unit_price,monthly_amount,starts_on) values(c,v,svc,rp,'weekly',4,2,150,300,d) returning id into sub;
 insert into public.package_subscriptions(client_id,vehicle_id,service_id,recurring_plan_id,frequency,visits_per_month,package_units,unit_price,monthly_amount,starts_on) values(c,v2,svc,rp2,'weekly',4,2,150,300,d) returning id into sub2;
 insert into public.package_charges(subscription_id,client_id,vehicle_id,service_id,competence_month,due_date,frequency,visits_per_month,package_units,unit_price,amount,gross_monthly_amount) values(sub,c,v,svc,d,d,'biweekly',2,1,150,150,150);
 update public.schedule_week_rules set enabled=true,max_teams=100;
 -- Exercise normal scheduling and completion transitions.
 insert into public.teams(name) select 'PLAN TEST TEAM '||i from generate_series(1,100) i;
 insert into public.appointments(client_id,vehicle_id,service_id,recurring_plan_id,starts_at,duration_minutes,status,source,base_value,final_value)
 select c,v,svc,rp,((d+i)+time '08:00') at time zone 'America/Sao_Paulo',60,'scheduled','internal',0,0 from generate_series(1,4) i;
 select id into ap from public.appointments where recurring_plan_id=rp order by starts_at limit 1;
 update public.appointments set status='cancelled' where recurring_plan_id=rp and (starts_at at time zone 'America/Sao_Paulo')::date=d+4;
 insert into public.appointments(client_id,vehicle_id,service_id,recurring_plan_id,starts_at,duration_minutes,status,source,base_value,final_value) values(c,v2,svc,rp2,(d+time '08:00') at time zone 'America/Sao_Paulo',60,'scheduled','internal',0,0);
 insert into public.appointments(client_id,vehicle_id,service_id,recurring_plan_id,starts_at,duration_minutes,status,source,base_value,final_value) values(c,v,svc,rp,((m-1)+time '22:00') at time zone 'America/Sao_Paulo',60,'scheduled','internal',0,0);
 for fixture in select id from public.appointments where recurring_plan_id in (rp,rp2) and status='scheduled' and not (recurring_plan_id=rp and (starts_at at time zone 'America/Sao_Paulo')::date=d+3) loop
  update public.appointments set status='confirmed' where id=fixture.id;
  update public.appointments set status='in_progress' where id=fixture.id;
  perform public.complete_job_without_photo(fixture.id,'Teste de conclusão sem fotografia.');
 end loop;
 r:=public.get_client_plan_control(c,d);select x into s from jsonb_array_elements(r->'subscriptions') x where x->>'id'=sub::text;
 if (s->>'completed')::int<>3 or (s->>'scheduled')::int<>1 or (s->>'limit_visits')::int<>2 then raise exception 'FAIL usage/snapshot/timezone %',s;end if;
 insert into plan_test_results values('completed vs scheduled/cancelled, monthly snapshot and Sao Paulo boundary','PASS');
 select x into s from jsonb_array_elements(r->'subscriptions') x where x->>'id'=sub2::text;
 if (s->>'completed')::int<>1 or s->>'limit_source'<>'unknown' or s->>'limit_visits' is not null then raise exception 'FAIL separate vehicle/historical limit';end if;
 insert into plan_test_results values('vehicle isolation and unknown historical quota','PASS');
 r:=public.get_client_plan_control(c,m);select x into s from jsonb_array_elements(r->'subscriptions') x where x->>'id'=sub::text;
 if (s->>'completed')::int<>0 or (s->>'limit_visits')::int<>4 or s->>'limit_source'<>'current_contract' then raise exception 'FAIL current fallback';end if;
 insert into plan_test_results values('current contract fallback and month isolation','PASS');
 select count(*) into before_charges from public.package_charges;select count(*) into before_appointments from public.appointments;
 e:=public.register_package_service(sub,d+1,'Aplicação de hidrorrepelente','Teste',ap,key);
 e2:=public.register_package_service(sub,d+1,'Aplicação de hidrorrepelente','Teste',ap,key);
 if e<>e2 then raise exception 'FAIL retry';end if;
 r:=public.get_client_plan_control(c,d);select x into s from jsonb_array_elements(r->'subscriptions') x where x->>'id'=sub::text;
 if jsonb_array_length(s->'services')<>1 or (s->>'completed')::int<>3 or before_charges<>(select count(*) from public.package_charges) or before_appointments<>(select count(*) from public.appointments) then raise exception 'FAIL benefit finance/count';end if;
 insert into plan_test_results values('dated benefit retry creates one record, no charge or extra visit','PASS');
 blocked:=false;begin perform public.register_package_service(sub,d+2,'Enceramento manual','',null,key);exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL reused key';end if;
 blocked:=false;begin perform public.register_package_service(sub2,d+1,'Enceramento manual','',ap,gen_random_uuid());exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL wrong vehicle link';end if;
 blocked:=false;begin perform public.register_package_service(sub,d-1,'Enceramento manual','',null,gen_random_uuid());exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL before start';end if;
 blocked:=false;begin perform public.register_package_service(sub,current_date+2,'Enceramento manual','',null,gen_random_uuid());exception when others then blocked:=true;end;if not blocked then raise exception 'FAIL future';end if;
 insert into plan_test_results values('reject changed retry payload, wrong vehicle link, future/precontract dates','PASS');
 perform public.void_package_service(e,'Lançamento incorreto');
 r:=public.get_client_plan_control(c,d);select x into s from jsonb_array_elements(r->'subscriptions') x where x->>'id'=sub::text;
 if jsonb_array_length(s->'services')<>0 or not exists(select 1 from public.package_service_events where id=e and voided_by=owner_id and void_reason='Lançamento incorreto') then raise exception 'FAIL void audit';end if;
 insert into plan_test_results values('soft void hides benefit and preserves audit','PASS');
 perform set_config('request.jwt.claim.sub',operator_id::text,true);
 blocked:=false;begin perform public.get_client_plan_control(c,d);exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL operator read';end if;
 blocked:=false;begin perform public.register_package_service(sub,d+1,'Enceramento manual','',null,gen_random_uuid());exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL operator write';end if;
 blocked:=false;begin perform public.void_package_service(e,'Teste de permissão');exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL operator void';end if;
 perform set_config('request.jwt.claim.sub','',true);perform set_config('request.jwt.claims','{}',true);
 blocked:=false;begin perform public.get_client_plan_control(c,d);exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL null auth';end if;
 perform set_config('request.jwt.claim.sub',owner_id::text,true);update public.app_profiles set active=false where user_id=owner_id;
 blocked:=false;begin perform public.get_client_plan_control(c,d);exception when insufficient_privilege then blocked:=true;end;if not blocked then raise exception 'FAIL inactive';end if;
 insert into plan_test_results values('operator, anonymous and inactive access denied','PASS');
 if has_function_privilege('anon','public.get_client_plan_control(uuid,date)','EXECUTE') or has_table_privilege('authenticated','public.package_service_events','INSERT') or has_table_privilege('authenticated','public.package_service_events','UPDATE') or not (select relrowsecurity from pg_class where oid='public.package_service_events'::regclass) then raise exception 'FAIL grants/RLS';end if;
 insert into plan_test_results values('RLS enabled, direct writes and anonymous RPC denied','PASS');
end $test$;
select * from plan_test_results;
rollback;
