begin;
create temporary table override_test_results(test text,result text);
do $test$
declare c uuid; v1 uuid; v2 uuid; v3 uuid; svc uuid; tm uuid; worker uuid; d date:=current_date+180;
 owner_id uuid:='11111111-1111-4111-8111-111111111111'; admin_id uuid:='22222222-2222-4222-8222-222222222222'; operator_id uuid:='33333333-3333-4333-8333-333333333333';
 r jsonb; r2 jsonb; ap uuid; rp uuid; blocked boolean;
begin
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 insert into public.clients(name) values('TEST ADM OVERRIDE') returning id into c;
 insert into public.vehicles(client_id,brand,model) values(c,'TEST','ONE') returning id into v1;
 insert into public.vehicles(client_id,brand,model) values(c,'TEST','TWO') returning id into v2;
 insert into public.vehicles(client_id,brand,model) values(c,'TEST','THREE') returning id into v3;
 insert into public.services(name,category,price,duration_minutes) values('TEST OVERRIDE','Estética',150,90) returning id into svc;
 insert into public.teams(name) values('TEST OVERRIDE') returning id into tm;
 insert into public.collaborators(name) values('TEST OVERRIDE') returning id into worker;
 update public.schedule_week_rules set enabled=true,max_teams=1 where weekday=extract(dow from d);
 insert into public.appointments(client_id,vehicle_id,service_id,team_id,starts_at,duration_minutes,status,source,base_value,final_value)
 values(c,v1,svc,tm,(d+time '08:00') at time zone 'America/Sao_Paulo',90,'scheduled','internal',150,150);
 blocked:=false;
 begin perform public.create_multi_vehicle_booking_recurring(c,array[v2],svc,d,time '08:00','[]',tm,null,'','test-normal-block'); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL normal booking not blocked'; end if;
 insert into override_test_results values('normal capacity/team conflict blocked','PASS');
 insert into public.recurring_plans(client_id,vehicle_id,service_id,frequency,weekday,local_time,start_date,base_value,discount_percent,final_value,active)
 values(c,v2,svc,'weekly',extract(dow from d)::smallint,time '08:00',d,150,0,150,true) returning id into rp;
 r:=public.create_admin_schedule_override(c,array[v2],svc,d,time '08:00',tm,null,'','test-admin-override','Equipe confirmou capacidade extra.');
 ap:=(r->'appointment_ids'->>0)::uuid;
 if not exists(select 1 from public.appointments where id=ap and schedule_override and schedule_override_by=owner_id and schedule_override_at is not null and final_value=150) then raise exception 'FAIL override/audit'; end if;
 insert into override_test_results values('owner overlap/capacity override, correct value and audit','PASS');
 if not exists(select 1 from public.recurring_plans where id=rp and active) then raise exception 'FAIL override disabled recurrence'; end if;
 insert into override_test_results values('existing recurring plan remains active','PASS');
 r2:=public.create_admin_schedule_override(c,array[v2],svc,d,time '08:00',tm,null,'','test-admin-override','Equipe confirmou capacidade extra.');
 if r2->'appointment_ids'<>r->'appointment_ids' then raise exception 'FAIL retry idempotency'; end if;
 insert into override_test_results values('retry creates no duplicate','PASS');
 blocked:=false;
 begin perform public.create_admin_schedule_override(c,array[v2],svc,d,time '08:00',tm,null,'','test-vehicle-duplicate','Equipe confirmou capacidade extra.'); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL vehicle duplicate accepted'; end if;
 insert into override_test_results values('same vehicle overlap remains blocked','PASS');
 blocked:=false;
 begin insert into public.appointments(client_id,vehicle_id,service_id,starts_at,duration_minutes,status,source,base_value,final_value,schedule_override,schedule_override_by,schedule_override_at,schedule_override_reason)
 values(c,v3,svc,(d+time '08:00') at time zone 'America/Sao_Paulo',90,'scheduled','internal',150,150,true,owner_id,now(),'Fake authorization'); exception when others then blocked:=true; end;
 if not blocked then raise exception 'FAIL forged flag'; end if;
 insert into override_test_results values('direct forged override blocked','PASS');
 perform set_config('request.jwt.claim.sub',admin_id::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',admin_id,'role','authenticated')::text,true);
 r:=public.create_admin_schedule_override(c,array[v3],svc,d,time '08:00',null,worker,'','test-manager-override','Equipe confirmou capacidade extra.');
 insert into override_test_results values('admin authorized','PASS');
 perform set_config('request.jwt.claim.sub',operator_id::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',operator_id,'role','authenticated')::text,true);
 blocked:=false;
 begin perform public.create_admin_schedule_override(c,array[v3],svc,d,time '12:00',null,worker,'','test-operator','Equipe confirmou capacidade extra.'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'FAIL operator'; end if;
 insert into override_test_results values('operator cannot override','PASS');
 perform set_config('request.jwt.claim.sub','',true);
 perform set_config('request.jwt.claims','{}',true);
 blocked:=false;
 begin perform public.create_admin_schedule_override(c,array[v3],svc,d,time '12:00',null,null,'','test-anon','Equipe confirmou capacidade extra.'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'FAIL anonymous'; end if;
 insert into override_test_results values('null auth cannot override','PASS');
 if has_function_privilege('anon','public.create_admin_schedule_override(uuid,uuid[],uuid,date,time,uuid,uuid,text,text,text)','EXECUTE') then raise exception 'FAIL anon execute'; end if;
 insert into override_test_results values('anon execute revoked','PASS');
 perform set_config('request.jwt.claim.sub',owner_id::text,true);
 perform set_config('request.jwt.claims',jsonb_build_object('sub',owner_id,'role','authenticated')::text,true);
 update public.app_profiles set active=false where user_id=owner_id;
 blocked:=false;
 begin perform public.create_admin_schedule_override(c,array[v3],svc,d,time '12:00',null,null,'','test-inactive','Equipe confirmou capacidade extra.'); exception when insufficient_privilege then blocked:=true; end;
 if not blocked then raise exception 'FAIL inactive'; end if;
 insert into override_test_results values('inactive admin cannot override','PASS');
 update public.app_profiles set active=true where user_id=owner_id;
 perform 1 from private.v2_read_appointments() where id=ap;
 insert into override_test_results values('typed reader remains compatible','PASS');
 update public.appointments set status='cancelled' where id=ap;
 if not exists(select 1 from public.appointments where id=ap and status='cancelled' and schedule_override) then raise exception 'FAIL cancel override'; end if;
 insert into override_test_results values('override can be cancelled, audit preserved','PASS');
 r:=public.create_admin_schedule_override(c,array[v3],svc,d,time '12:00',null,worker,'','test-completion','Equipe confirmou capacidade extra.');
 ap:=(r->'appointment_ids'->>0)::uuid;
 update public.appointments set status='confirmed' where id=ap;
 update public.appointments set status='in_progress' where id=ap;
 perform public.complete_job_without_photo(ap,'Justificativa de teste de conclusão sem foto.');
 if not exists(select 1 from public.appointments where id=ap and status='completed' and schedule_override) then raise exception 'FAIL override completion'; end if;
 insert into override_test_results values('override completes with normal completion/finance flow','PASS');
end $test$;
select * from override_test_results;
rollback;
